### ISSUE TITLE
Message not sent to exchange created under other than root / host

### ISSUE THREAD

**Issue by byugandhara1** [SolaceSamples/solace-samples-amqp-qpid-proton-python#3]
My scenario is to send message to particular exchange "test_exchange" created under vhost "test_vhost". To achieve this I am adding vhost name at the time connection in connect function
conn = event.container.connect(
                url=self.url,
                user=self.username,
                password=self.password,
                allow_insecure_mechs=True, virtual_host="test_vhost")
After connection it gives connection success logs

api_1       | INFO:proton:Connecting to Url('amqp://rabbitmq:5672')...
api_1       | INFO:proton:Connected to http://localhost:9001

But at message send it fails to connect with exchange and gives following error
api_1       | ERROR:proton:NOT_FOUND - no exchange 'test_exchange' in vhost '/'

**Comment by TamimiGitHub** [comment]
A couple of questions that might help guide the issue:
1. Have you attempted to use the default exchange in the vhost (empty string)? 
2. How did you creating `test_exchange`?
3. How are you setting the exchange name in your message when you are sending it in your code?

if the exchange name is specified, and that exchange does not exist, the server will raise a channel exception.

Note: issue raised on this repo are for the solace samples in particular.

**Comment by aaron-613** [comment]
Hi @byugandhara1 , trying to figure out & close this old issue.  I notice in the logs snippet you posted, it references RabbitMQ.  Note that Rabbit uses an older version of AMQP: 0-9-1.  This is incompatible with 1.0.  Please confirm what type of broker you're trying to connect to, and any further information that would be useful to debug.  Thanks!

**Comment by Mrc0113** [comment]
Closing as stale.
